
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eda-dev
  labels:
    app: order-service
spec:
  selector:
    app: order-service-container
  ports:
    - name: order-service
      port: 8083
      protocol: TCP
      targetPort: 8083
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: eda-dev
  labels:
    app: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-container
  template:
    metadata:
      labels:
        app: order-service-container
    spec:
      containers:
        - name: order-service-container
          image: aleson/order-service:latest
          ports:
            - containerPort: 8083
              name: rest
            - containerPort: 30301
              name: postgres
            - containerPort: 9092
              name: kafka