apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: eda-dev
  labels:
    app: zookeeper-service
spec:
  type: NodePort
  ports:
  - name: zookeeper-port
    port: 2181
    targetPort: 2181
    nodePort: 30001
  selector:
    app: zookeeper

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: eda-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: library/zookeeper:3.4.13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"